settings:
  disabled_events: [event1, event2, event3]
  commit_msg: "Last Fresh."
  max_lines: 0
  readme_file: "./README.md"
  date:
    timezone: "GMT+08:00"
    text: "<i>Last refresh</i>: <b>{DATE}</b>"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
